test: &default

  # Credentials for REST APIs
  client_id: ATE1BuhMfJXR71LjW_EY8IUD7BgeoMzIC60GbUufKWW9KSdmLpiymUVxP_CbKwKcDWUSpnqJGEUwoKto
  client_secret: EIY2q9UcANgGSzbDPkUZIuyKMH7sXAClldi6NkUtl3-iMBywLmRFFVXOEGa6mndPPGwvWGe7Jk9QrQ9E

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: codigofacilito@lalo.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
